### PR TITLE
Update Component Generator to get default value in runtime

### PR DESCRIPTION
**Pull request by Dreamescaper**
Contributes to #309 (.1)

Currently Generator retrieves actual BindableProperty's DefaultValue, and attempts to generate expression for this value. 
This approach has multiple issues:
- Ability to generate expressions for values is limited (and not really easy).
- Retrieving actual BindableProperty is not very reliable, e.g. it fails for some Xamarin Community Toolkit controls (because of Device.GetNamedSize usage).
- It's not possible to use Source Generator approach (if we decide to go this way).

This PR replaces expressions generation with simply using BindableProperty's DefaultValue in runtime (I assign them to static readonly fields in Handlers).

### CODE REVIEW

**Comment by Dreamescaper** [comment]
Build is failed because one of the BindableProperties is deprecated.
Should we generate such properties at all?
Or add deprecated attribute to generated property?

We can also add auto-generated tag to generated files as well to disable analyzers for those files.

**Comment by Eilon** [comment]
> We can also add auto-generated tag to generated files as well to disable analyzers for those files.

We should definitely do that! I thought maybe it auto-ignores `.generated.cs` files but perhaps we need to explicitly add an attribute to the class?

Anyway this change is great! I was just thinking about it this morning after I woke up but you beat me to it 😄 

I'm not so sure about the `#region`s though. They're so.... .NET 1.0... 😁

**Comment by Dreamescaper** [comment]
Seems like auto-generated tag does not help from deprecated usage warnings, so I simply disabled this diagnostic for generated files in .editorconfig file. 
Let me know if there are any concerns about such approach.

Removed regions as well.

**Comment by Eilon** [comment]
This is a good change, thank you! I never liked loading Xamarin.Forms and _running_ it during component generation!

**Pull request merged**
