### PR TITLE
Upgrade Xamarin.Forms to 5.0

### LINKED ISSUE #277: Xamarin Forms 5 breaking changes
Xamarin Forms 5 will come out of pre-release any day now and there are some breaking changes. https://github.com/xamarin/Xamarin.Forms/issues/11857

I think the only one that will affect us will be the migration from MasterDetail to FlyoutView.

Is our goal to upgrade to Xamarin Forms 5 shortly after it goes GA? I think it should be.

### PR DESCRIPTION
**Pull request by Dreamescaper**
Resolves #277.

- Upgraded `Xamarin.Forms` to 5.0.0.1874,
- Upgraded `Xamarin.Essentials` to 1.6.0,
- Updated Android projects to use TargetFrameworkVersion v9.0 -> v10.0,
- Updated Android projects to use android:targetSdkVersion 28 -> 29,
- Removed `System.Numerics.Vectors` reference from Android projects (I don't think it's needed, and it causes version conflict warnings),
- Removed references to Xamarin.AndroidX.* packages from Microsoft.MobileBlazorBindings.WebView.Android - they are already included in scope of other packages, and caused version conflict after XF upgrade,
- Regenerated components
- Replaced MasterDetailPage component with FlyoutPage component

### CODE REVIEW

**Comment by Dreamescaper** [comment]
There are two things I wasn't able to check in this branch:
- iOS. Unfortunately, I have no Mac and no iOS devices.
- FlyoutPage. I think I've updated MasterDetailPage components correctly, but I wasn't able to make it work. However, I wasn't able to make MasterDetailPage work in current master either. Do we have any samples somewhere?

**Comment by Dreamescaper** [comment]
Seems like CI is not happy with android:targetSdkVersion update.
But the build fails otherwise, and it seems like targetSdkVersion 29 or higher is enforced by Google as well.

**Comment by Eilon** [comment]
Wow, very nice work @Dreamescaper ! I'll take a look so we can get this merged in!

**Comment by lachlanwgordon** [comment]
For the MasterDetailPage, it turns out to not be a breaking change in XF 5, just marked as deprecated. I've done the migration to Flyout in non MBB apps and it's just a few name changed.

I've never tried the MasterDetail in MBB so I'm not sure if it ever worked, but I saw that the classes exist.

**Comment by Eilon** [comment]
Well, the PR works on my machine! I'll start digging into this more as well as the Master Details thing. I'm sure I've used it before, but probably a LONG time ago.

**Comment by Eilon** [comment]
I have FlyoutPage working fine, but it's a bit tricky to use due to how Mobile Blazor Bindings async startup works.

Here's what you would do in your App's constructor:

```c#
            var mainPage = new FlyoutPage
            {
                Flyout = new ContentPage() { Title = "My App", }, // Title is required
                Detail = new ContentPage()
            };
            MainPage = mainPage;
            host.AddComponent<FlyoutPageView>(parent: mainPage.Flyout);
            host.AddComponent<DetailPageView>(parent: mainPage.Detail);
```

Where `FlyoutPageView` and `DetailPageView` are both Blazor components that have a top-level view such as `ContentView`, `Frame`, etc.

So, no real problem with FlyoutPage in technical terms, but the experience is less than ideal (it always has been).

**Comment by Eilon** [comment]
I think this is good to go! It was such "fun" getting Android SDK level 29 to install on the CI machine 😄

**Comment by Eilon** [comment]
Thank you again @Dreamescaper for the wonderful work and @lachlanwgordon for the info on breaking changes (or lack of them)!

**Comment by Dreamescaper** [comment]
@Eilon 
Sorry for that pain :)
Thanks a lot!

**Comment by Eilon** [comment]
I mean, I got to create this file in the change:

https://github.com/xamarin/MobileBlazorBindings/blob/master/azure-pipelines/yes.txt

So it wasn't _all_ pain. That file is wonderful 😄

**Pull request merged**
