### PR TITLE
Allow specifying userdata folder for webview

### LINKED ISSUE #196: HybridApp Windows WPF Webview doesn't render.
Running the default template for hybrid apps does not render the webview when using the Windows WPF project.

### PR DESCRIPTION
**Pull request by Kukks**
I haven't put a lot of effort into this but it does seem like a relatively simple fix. Fixes #196

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/MobileBlazorBindings?pullRequest=230) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/MobileBlazorBindings?pullRequest=230) before we can accept your contribution.<br/><br/>:x: Kukks [sign now](https://cla.dotnetfoundation.org/xamarin/MobileBlazorBindings?pullRequest=230)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/MobileBlazorBindings?pullRequest=230) it.</sub>

**Comment by jspuij** [comment]
You beat me to it @Kukks. The API is fine. I was however thinking to use

```
Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), <applicationName>) ;
```

to use as the default folder. This way it ends up in the %AppData%\Local\<applicationName> folder on the disk.

Now then onto the applicationName variable. You are using Assembly.GetEntryAssembly(), but this can actually be NULL in some circumstances (like when embedding the runtime, or during unit tests etc).

So my idea was to have something like this for uniqueNameForApp:

```
var applicationName = (Assembly.GetEntryAssembly() ?? Assembly.GetCallingAssembly()).GetName().Name;
```

Whole definition of init would be then:

```
        public static void Init(string webviewDirectory = null)
        {
            if (webViewDirectory == null)
            {
                var applicationName = (Assembly.GetEntryAssembly() ?? Assembly.GetCallingAssembly()).GetName().Name;
                webviewDirectory = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), applicationName) ;
            }
            WebViewDirectory = webviewDirectory;
            // Calling this means the assembly will be loaded, so Xamarin.Forms will discover its ExportRenderer attributes
        }
```

That way we also have a nice default when somebody does not specify a parameter to Init.

Does this make sense? And subsequently, could you amend your PR?

**Comment by jspuij** [comment]
I've amended the PR. It's now #246.

**Comment by Kukks** [comment]
> I've amended the PR. It's now #246.

Cool, thanks for the  review and amends. :)

**Pull request closed without merging**
