### PR TITLE
Fix elements removal for non-Layout parent

### LINKED ISSUE #217: Using AuthorizeView with Shell
I'm trying to use asp net core auth with Mobile Blazor (by registering custom `AuthenticationStateProvider` and storing jwt token in SecureStorage) and use AuthorizedView component. So I want to show login page when user is not authenticated, so I'm trying to do something like that:
```razor
<CascadingAuthenticationState>
    <Shell>
        <AuthorizeView>
            <Authorized>
                <TabBar>
					<Tab Icon="Icons.Home">
					    <HomePage />
					</Tab>
					<Tab Icon="Icons.Person">
					    <ProfilePage />
					</Tab>
                </TabBar>
            </Authorized>
            <NotAuthorized>
                <TabBar>
                    <Mobile.Pages.LoginPage />
                </TabBar>
            </NotAuthorized>
        </AuthorizeView>
    </Shell>
</CascadingAuthenticationState>

```

And it basically works - with the exception of refreshing when state changes. So if I log in or log out, I have to reopen the app to see updated results.
I've tried injecting `AuthenticationStateProvider`, and invoke `StateHasChanged` explicitly on `AuthenticationStateChanged` event, but that has no effect.

I've also tried to put AuthorizedView inside TabBar:
```razor
                <TabBar>
			        <AuthorizeView>
			            <Authorized>
							<Tab Icon="Icons.Home">
							    <HomePage />
							</Tab>
							<Tab Icon="Icons.Person">
							    <ProfilePage />
							</Tab>
			            </Authorized>
			            <NotAuthorized>
			                <Tab>
			                    <Mobile.Pages.LoginPage />
			                </Tab>
			            </NotAuthorized>
		        	</AuthorizeView>
               	</TabBar>
```
This way I can see at least some updates - new tabs are added, but never removed from Shell (so I see login page as separate tab after logout).

Is there anything I do wrong here?
Thanks!

### PR DESCRIPTION
**Pull request by Dreamescaper**
fixes #217 

- `ElementManager`'s method `RemoveElement(IElementHandler handler)` is replaced with `RemoveChildElement(IElementHandler parentHandler, IElementHandler childHandler)`
- Instead of handling child's element removal in MobileBlazorBindingsElementManager, it delegates removal to parent's `RemoveChild` method.
- Implemented `RemoveChild` method for all container elements handlers.
- Fixed `AddChild` method for some Shell controls handlers to handle `physicalSiblingIndex` argument.

Implementing `RemoveChild` for some Shell elements was a little bit tricky - because of implicit conversions `AddChild` method can actually add multiple elements, and we need to identify which ShellItem to remove (e.g. when you add `TemplatedPage` to `Shell` it actually adds `ShellItem` -> `ShellSection` -> `ShellContent` -> `TempletedPage`).

I decided to move methods `AddChild` and `RemoveChild` to separate interface `IXamarinFormsContainerElementHandler`, it seemed like a better option to me. Let me know if you'd prefer it other way.

Example:
<details>
  <summary>AppShell.razor</summary>

  ```razor
<Shell>
    <TabBar>
        @if (firstTabDisplayed)
        {
            <Tab Title="Tab1">
                <ContentPage>
                    <StackLayout>
                        <Label Text="Tab1" />
                        <Button Text="Switch tab" OnClick="SwitchTab" />
                    </StackLayout>
                </ContentPage>
            </Tab>
        }
        else
        {
            <Tab Title="Tab2">
                <ContentPage>
                    <StackLayout>
                        <Label Text="Tab2" />
                        <Button Text="Switch tab" OnClick="SwitchTab" />
                    </StackLayout>
                </ContentPage>
            </Tab>
        }
    </TabBar>
</Shell>

@code { 
    bool firstTabDisplayed = true;

    void SwitchTab()
    {
        firstTabDisplayed = !firstTabDisplayed;
    }
}
  ```
  
</details>

<details>
<summary>Before</summary>

4CsyhaXgu8

</details>

<details>
<summary>After</summary>

hQfoqSL9E1

</details>

### CODE REVIEW

**Comment by Dreamescaper** [comment]
Open question. I don't know how to handle `MenuItem` removal from `Shell` properly. Thing is that implicit conversion to `ShellItem` wraps it in `MenuShellItem`, which is internal type. Therefore, I'm not sure how to identify corresponding ShellItem properly.
Currently I use something like that:
```csharp
        private XF.ShellItem GetItemForMenuItem(XF.MenuItem childAsMenuItem)
        {
            // MenuItem is wrapped in ShellMenuItem, which is internal type.
            // Not sure how to identify this item correctly.
            return ShellControl.Items.FirstOrDefault(item => item.Title == childAsMenuItem.Text 
                && item.Items.Count == 0);
        }
```

**Comment by Eilon** [comment]
Wow very nice, I will take a close look at this change!

I agree that comparing the title/text is not good because it won't be reliable. I'll see if I can come up with some way to work around the internal type problem.

**Comment by Eilon** [comment]
@Dreamescaper I pushed a couple of small changes to the branch so we can improve the check for MenuShellItem. I'll do some additional testing on the change and if it's all good, I'll merge.

**Comment by Dreamescaper** [comment]
<details>
<summary>Image</summary>

image

</details>


Probably would be better to continue discussion here.
I haven't seen such issue, let me know how to reproduce that if you need any help.

**Comment by Eilon** [comment]
@Dreamescaper I pushed a change that updates the ControlGallery sample. If you run it (I ran on iOS Simulator) you can add as many Tabs as you want, but if you go to a tab and add a ShellContent, you get that exception.

**Comment by Eilon** [comment]
BTW I doubt this is a regression because this scenario was never well tested before. I think this PR is a huge step forwards in the design and implementation so depending on how things go, we could take this PR after I do a bit more testing, and leave the rest for a follow-up investigation.

**Comment by Eilon** [comment]
I pushed a change that adds a Remove button as well. Weirdly, you can remove & add tabs, but you can only remove shell contents! Adding shell contents is not allowed.

**Comment by Dreamescaper** [comment]
Seems like you can add contents, but only if your selected tab is not the last one.

**Comment by Eilon** [comment]
Hmm I'm not able to add any Shell Contents ever (after the initial load). No matter where I am in the Control Gallery sample, clicking `Add Shell Content` always throws.

**Comment by Eilon** [comment]
I checked the sample app code on the master branch and it confirmed that this isn't a regression.

On master I can add but not remove tabs. And I can't add or remove shell contents at all.

**Comment by Dreamescaper** [comment]
So adding the following line to ShellSectionHandler.AddChild solves the issue for me:
```csharp
            contentToAdd.Content ??= new XF.Page();
```

But I don't get why doesn't it fail during initial load, and why it doesn't fail for me for some tabs.

**Comment by Eilon** [comment]
How did you get adding/removing shell content to work? I still can't get that to work at all.

As far as initial load working, there were some recent changes to Shell that might have affected that due to some bug reports I filed on Xamarin.Forms. Not sure if it's related, but the point is that initial load in Xamarin.Forms sometimes has slightly different behavior than what happens once it's all up and running.

**Comment by Dreamescaper** [comment]
I've pushed workaround to branch.

**Comment by Dreamescaper** [comment]
I also get the following exception from time to time (I'm testing on Android emulator):
```
'The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 5, found: 4 Pager id: 8 Pager class: class crc64720bb2db43a66fe9.FormsViewPager Problematic adapter: class crc643f46942d9dd1fff9.ShellFragmentPagerAdapter'
```

That looks more like Xamarin.Forms bug though

**Comment by Eilon** [comment]
That workaround lets me _add_ shell contents - _sometimes_. And depending on which shell content I remove, sometimes it works, sometimes I get a NullRef error page, and sometimes the app insta-crashes and disappears.

**Comment by Dreamescaper** [comment]
I get Android exception even if I remove element directly from NativeControl, so that's certainly Xamarin.Forms bug.

**Comment by Eilon** [comment]
Pushed another change to update some other controls that are containers and should implement the new `IXamarinFormsContainerElementHandler` interface (yay!) and also removed unused code from controls that were never containers and don't need an `AddChild` method. Double-yay!

**Comment by Dreamescaper** [comment]
Investigated why Tab name for added Shell Content is not displayed immediately. 
We add empty content first, and then set all attributes, including title. 
And seems like Xamarin does not like that.

I can see same behavior for the following code:

<details>
<summary>Code</summary>

```csharp
    void AddShellContentDirectly()
    {
        var content = new Xamarin.Forms.ShellContent
        {
            Content = new Xamarin.Forms.ContentPage
            {
                Content = new Xamarin.Forms.StackLayout
                {
                }
            }
        };
        tab.NativeControl.Items.Add(content);

        content.Title = "Added directly";
    }
```

</details>

<details>
<summary>Recording</summary>

pkRX8bq2Lh

</details>


So I suppose that's Xamarin bug as well, not sure how valid this scenario is.

**Comment by Eilon** [comment]
@Dreamescaper I'm pretty happy with where this is right now. I very much appreciate all your work on this!

I'm thinking it would be best to merge this PR as it is now and we can deal with any other issues as follow-up PRs. Does that seem reasonable to you?

**Comment by Dreamescaper** [comment]
Sure!

**Pull request merged**
